In [2]:
import h5py
import numpy as np

In [4]:
f = h5py.File('/eos/user/k/kvadla/ntuples/hdf5/SUSY2_Signal_mc16a/2L2J_flat_signal_C1N2_WZ_200_100.h5', 'r')

In [9]:
list(f.keys())

[u'FlatTree']

In [37]:
dset = f['FlatTree']
dset.shape

(5827,)

In [20]:
dset.dtype

dtype([('Ht30', '<f4'), ('METOverPtW', '<f4'), ('METOverPtZ', '<f4'), ('Ptll', '<f4'), ('Rjj', '<f4'), ('Rll', '<f4'), ('dPhiPjjMet', '<f4'), ('dPhiPllMet', '<f4'), ('eventWeights', '<f8'), ('jetPt1', '<f4'), ('jetPt2', '<f4'), ('lepPt1', '<f4'), ('lepPt2', '<f4'), ('met_Et', '<f4'), ('mjj', '<f4'), ('mll', '<f4'), ('mt2leplsp_0', '<f4'), ('nBJet20_MV2c10_FixedCutBEff_77', '<i4'), ('nJet30', '<i4')])

In [14]:
list(dset.dtype.names)

['Ht30',
 'METOverPtW',
 'METOverPtZ',
 'Ptll',
 'Rjj',
 'Rll',
 'dPhiPjjMet',
 'dPhiPllMet',
 'eventWeights',
 'jetPt1',
 'jetPt2',
 'lepPt1',
 'lepPt2',
 'met_Et',
 'mjj',
 'mll',
 'mt2leplsp_0',
 'nBJet20_MV2c10_FixedCutBEff_77',
 'nJet30']

In [49]:
ndarray = np.array(dset[:].tolist())
ndarray.shape

(5827, 19)

In [39]:
event_weights_array = np.array(dset['eventWeights'].tolist())
event_weights_array.shape

(5827,)

In [31]:
features = list(dset.dtype.names)
len(features)

19

In [60]:
selected_features_mask = np.array([feature != 'eventWeights' for feature in features])
selected_features_mask

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [57]:
ndarray[0]

array([ 2.20704529e+02,  1.56190246e-01,  1.59430578e-01,  1.31377075e+02,
        2.04370356e+00,  1.86016142e+00, -2.70735312e+00,  7.16477454e-01,
        2.87476227e-06,  1.21500511e+02,  9.92040100e+01,  1.30772354e+02,
        2.25450764e+01,  2.09455242e+01,  2.02984207e+02,  9.36797638e+01,
        1.83810768e+01,  0.00000000e+00,  2.00000000e+00])

In [61]:
selected_features = ndarray[:,selected_features_mask]
selected_features.shape

(5827, 18)

In [62]:
selected_features[0]

array([ 2.20704529e+02,  1.56190246e-01,  1.59430578e-01,  1.31377075e+02,
        2.04370356e+00,  1.86016142e+00, -2.70735312e+00,  7.16477454e-01,
        1.21500511e+02,  9.92040100e+01,  1.30772354e+02,  2.25450764e+01,
        2.09455242e+01,  2.02984207e+02,  9.36797638e+01,  1.83810768e+01,
        0.00000000e+00,  2.00000000e+00])

In [ ]:
f.close()